lecteurcarte.o: lecteurcarte.cpp lecteurcarte.h lcarte.h \
 /shared/TCii/include/lcarte.h bouton.h \
 /shared/TCii/include/donnees_borne.h memoire_borne.h \
 /shared/TCii/include/memoire_borne.h \
 /shared/TCii/include/donnees_borne.h baseclient.h Generateur_save.h \
 memoire_borne.h prise.h voyant.h mode.h
borne.o: borne.cpp memoire_borne.h /shared/TCii/include/memoire_borne.h \
 /shared/TCii/include/donnees_borne.h \
 /shared/TCii/include/donnees_borne.h lecteurcarte.h lcarte.h \
 /shared/TCii/include/lcarte.h bouton.h memoire_borne.h baseclient.h \
 Generateur_save.h prise.h voyant.h mode.h
baseclient.o: baseclient.cpp baseclient.h lcarte.h \
 /shared/TCii/include/lcarte.h
voyant.o: voyant.cpp voyant.h /shared/TCii/include/donnees_borne.h \
 memoire_borne.h /shared/TCii/include/memoire_borne.h \
 /shared/TCii/include/donnees_borne.h
prise.o: prise.cpp prise.h memoire_borne.h \
 /shared/TCii/include/memoire_borne.h \
 /shared/TCii/include/donnees_borne.h \
 /shared/TCii/include/donnees_borne.h
timer.o: timer.cpp timer.h /shared/TCii/include/donnees_borne.h mem_sh.h \
 /shared/TCii/include/mem_sh.h /shared/TCii/include/donnees.h
Generateur_save.o: Generateur_save.cpp Generateur_save.h memoire_borne.h \
 /shared/TCii/include/memoire_borne.h \
 /shared/TCii/include/donnees_borne.h \
 /shared/TCii/include/donnees_borne.h prise.h voyant.h
bouton.o: bouton.cpp bouton.h /shared/TCii/include/donnees_borne.h \
 memoire_borne.h /shared/TCii/include/memoire_borne.h \
 /shared/TCii/include/donnees_borne.h
